[31/Mar/2019 21:04:42] "GET /e/linj121 HTTP/1.1" 200 37
[31/Mar/2019 21:04:43] "GET /e/linj121 HTTP/1.1" 200 37
[31/Mar/2019 21:04:43] "GET /e/linj121 HTTP/1.1" 200 37
[31/Mar/2019 21:04:43] "GET /e/linj121 HTTP/1.1" 200 37
[31/Mar/2019 21:04:43] "GET /e/linj121 HTTP/1.1" 200 37
[31/Mar/2019 21:04:43] "GET /e/linj121 HTTP/1.1" 200 37
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 31, 2019 - 21:04:31
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://localhost:10036/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 31, 2019 - 21:35:41
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://localhost:10036/
Quit the server with CONTROL-C.
[31/Mar/2019 21:44:05] "GET /e/linj121 HTTP/1.1" 200 37
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 31, 2019 - 21:43:27
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://localhost:10036/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 31, 2019 - 21:46:13
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://localhost:10036/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 31, 2019 - 21:53:24
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://localhost:10036/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 31, 2019 - 21:53:41
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://localhost:10036/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 31, 2019 - 21:56:18
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://localhost:10036/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fb23367b598>
Traceback (most recent call last):
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/linj121/CS1XA3/Project03/python_env/django_project/todoapp/models.py", line 12, in <module>
    class TodoList(models.Model): 
  File "/home/linj121/CS1XA3/Project03/python_env/django_project/todoapp/models.py", line 17, in TodoList
    category = models.ForeignKey(Category, default="general") 
TypeError: __init__() missing 1 required positional argument: 'on_delete'
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7ff7fcc71598>
Traceback (most recent call last):
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/linj121/CS1XA3/Project03/python_env/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/linj121/CS1XA3/Project03/python_env/django_project/todoapp/models.py", line 12, in <module>
    class TodoList(models.Model): 
  File "/home/linj121/CS1XA3/Project03/python_env/django_project/todoapp/models.py", line 17, in TodoList
    category = models.ForeignKey(Category, default="general") 
TypeError: __init__() missing 1 required positional argument: 'on_delete'
[31/Mar/2019 22:32:40] "GET /e/linj121 HTTP/1.1" 200 37
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 31, 2019 - 22:30:51
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://localhost:10036/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 22:38:52
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://localhost:10036/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 22:47:01
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://localhost:10036/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2019 - 22:56:58
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://localhost:10036/
Quit the server with CONTROL-C.
Not Found: /e/linj121/
[31/Mar/2019 23:13:43] "GET /e/linj121/ HTTP/1.1" 404 1981
